### ISSUE TITLE
Homework

### ISSUE THREAD

**Issue by martinop** [Bonsanto/web1-Assistance-2015B#1]
Hola Alberto, podria enviarte a tu correo o algo los problemas que mandaste el viernes? a ver si estan bien, que opinas y que le puedo mejorar.

**Comment by Bonsanto** [comment]
Crea un gist con los n archivos y me pasas el link https://gist.github.com

**Comment by martinop** [comment]
#3 Con este hice dos versiones, una a punta de solo colores y otra con dos imagenes.
Con imagenes: https://gist.github.com/martinop/7f34d51e497638f449d2
css: https://gist.github.com/martinop/14b0f6510e2d965dff0a
http://imgur.com/rmyfmdr,C3sAjbf

con Colores: https://gist.github.com/martinop/fec2b862b13385db2118
css:https://gist.github.com/martinop/aabed88fdc12b190cde2

Este primer problema creo que tiene fallas, porque no supe como hacer para que el height comenzara desde abajo, si no que coloque la temperatura al maximo y con un div "superpuesto" la voy colocando mas pequeña para simular el efecto.

#2 https://gist.github.com/martinop/21030eacc5c89db0916f Aunque me faltan arreglarle algunas cosas

#1 Aun no lo comencé.

btw, no se que clase de bug tengo pero no puedo asignarle a ninguna variable algún valor con document.getelementbyid o queryselector.

**Comment by martinop** [comment]
btw, no se que clase de bug tengo pero no puedo asignarle a ninguna variable algún valor con document.getelementbyid o queryselector.

**Comment by Bonsanto** [comment]
Por cierto los issues no son para mensajes, para eso se usan los direct messages
